#+TITLE: Vagrant
#+AUTHOR: Auralcat

* What it is
  Create virtual machines from preconfigured boxes

* Configuring the instance's name
  You need to change the hostname in site.yml.

* Getting started (WordPress)
  [[http://vccw.cc/][Reference]]
** Install VirtualBox
   [[https://www.virtualbox.org/][Official website]]
** Install Vagrant
   [[http://www.vagrantup.com/][Official website]]
** Install the vagrant-hostsupdater plugin. (Optional)
   #+BEGIN_SRC sh
   vagrant plugin install vagrant-hostupdater
   #+END_SRC
   *Windows does not allow to change hosts files. Please add vccw.test 192.168.33.10 by yourself!*
** Download vagrant box
   #+BEGIN_SRC sh
   vagrant box add vccw-team/xenial64
   #+END_SRC
** Download .zip
   [[https://github.com/vccw-team/vccw/releases/download/3.18.0/vccw-3.18.0.zip][Here]]
** Change into a new directory.
** Start a Vagrant environment.
   #+BEGIN_SRC sh
   vagrant up
   #+END_SRC
** Visit WordPress on the Vagrant in your browser
   Visit http://vccw.test/ or http://192.168.33.10/
** Environments
*** WordPress
    This tool installs a WordPress environment with these settings by default.

    Default user
    Username: admin
    Password: admin
*** MySQL
    MySQL Host: 127.0.0.1
    Username: wordpress or root
    Password: wordpress
    Port: 3306
*** SSH
    Host: vccw.test or 192.168.33.10
    Username: vagrant
    Password: vagrant
    Port: 22

    You can login virtual machine with:
    #+BEGIN_SRC sh
    vagrant ssh
    #+END_SRC
