#+TITLE: Vagrant
#+AUTHOR: Auralcat

* What it is
  Create virtual machines from preconfigured boxes

* Configuring the instance's name
  You need to change the hostname in site.yml.

* Getting started (WordPress)
  [[http://vccw.cc/][Reference]]
** Install VirtualBox
   [[https://www.virtualbox.org/][Official website]]
** Install Vagrant
   [[http://www.vagrantup.com/][Official website]]
** Install the vagrant-hostsupdater plugin. (Optional)
   #+BEGIN_SRC sh
   vagrant plugin install vagrant-hostupdater
   #+END_SRC
   *Windows does not allow to change hosts files. Please add vccw.test 192.168.33.10 by yourself!*
** Download vagrant box
   #+BEGIN_SRC sh
   vagrant box add vccw-team/xenial64
   #+END_SRC
** Download .zip
   [[https://github.com/vccw-team/vccw/releases/download/3.18.0/vccw-3.18.0.zip][Here]]
** Change into a new directory.
** Start a Vagrant environment.
   #+BEGIN_SRC sh
   vagrant up
   #+END_SRC
** Visit WordPress on the Vagrant in your browser
   Visit http://vccw.test/ or http://192.168.33.10/
** Environments
*** WordPress
    This tool installs a WordPress environment with these settings by default.

    Default user
    Username: admin
    Password: admin
*** MySQL
    MySQL Host: 127.0.0.1
    Username: wordpress or root
    Password: wordpress
    Port: 3306
*** SSH
    Host: vccw.test or 192.168.33.10
    Username: vagrant
    Password: vagrant
    Port: 22

    You can login virtual machine with:
    #+BEGIN_SRC sh
    vagrant ssh
    #+END_SRC
Customizing

VCCW is configured for those developing WordPress plugins, themes or websites. It includes many customizable variables for setting the WordPress version (or beta release), language, hostname, subdirectory, admin credentials, default plugins, default theme, multisite, SSL and other options. These variables give you a lot of flexibility in tailoring your development environment to your specific needs.

Copy provision/default.yml to site.yml like following.

$ cp provision/default.yml site.yml

Then edit the site.yml and run vagrant up.

Or place the site.yml and put variables like following.

hostname: example.com
ip: 192.168.33.11
lang: ja
plugins:
  - contact-form-7
  - jetpack
theme: twentysixteen

Then just run vagrant up.
Global configuration

VCCW has a series of global parameters which work with all virtual machines.

They can be specified ~/.vccw/config.yml like following.

memory: 1024
cpus: 2
lang: ja
theme_unit_test: true

Customizable variables

See provision/default.yml.

Back to top
Run pre/post provisioning scripts

You can place shell scripts, so it will run at pre/post provisioning.

    provision-pre.sh - Run before chef provisioning.
    provision-post.sh - Run after chef provisioning.

Example shell script.

provision-post.sh - It will run after provisioning.

#!/usr/bin/env bash

set -ex

/usr/local/bin/wp --path=/var/www/wordpress plugin install contact-form-7 --activate

This example script will install and activate plugin “Contact Form 7” by WP-CLI.
Customize with Ansible

Also, you can use Ansible.

provision-post.yml - It will run after provisioning.

- hosts: all
  become: yes

  tasks:

  - name: Ensure nginx is installed
    apt: pkg=nginx state=latest

Back to top
Checking Email with MailCatcher

MailCatcher re-routes all WordPress emails to Mailcatcher.

Please visit: http://vccw.test:1080/

* WP-CLI
  Community command that generates a VCCW environment.

  https://github.com/vccw-team/scaffold-vccw

** How to install
   #+BEGIN_SRC sh
   wp package install vccw/scaffold-vccw:@stable
   #+END_SRC
** How to use
   Generate a VCCW environment into the wp.dev directory.
   #+BEGIN_SRC sh
   wp scaffold vccw wp.dev
   cd wp.dev
   vagrant up
   #+END_SRC
** Usage
   #+BEGIN_SRC sh
   wp help scaffold vccw
   #+END_SRC
** Examples
   #+BEGIN_SRC sh results :raw
   wp scaffold vccw wordpress.dev
   #+END_SRC

   #+BEGIN_SRC sh
   wp scaffold vccw wordpress.dev --lang=ja
   #+END_SRC
